version: '3'

services:
  stateless-auth-db:
    container_name: stateless-auth-db 
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment: 
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: StrongPassword@
    networks:
      - auth
    ports:
      - "1433:1433"
  stateful-auth-db:
    container_name: stateful-auth-db 
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment: 
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: StrongPassword@
    networks:
      - auth
    ports:
      - "1434:1433"
  demo-redis:
    container_name: demo-redis
    image: redis:latest
    networks:
      - auth
    ports:
      - "6379:6379"
networks:
  auth:
    driver: bridge